### ISSUE TITLE
Error when computing logloss and not all classes present in test fold

### ISSUE THREAD

**Issue by pplonski** [openml/automlbenchmark#205]
During the analysis of the `wine-quality-white` dataset I got the error:

```py
Predictions saved to `/output/mljarsupervised_compete.openml_s_271.test.docker.20201203T093820/predictions/mljarsupervised_compete.wine-quality-white.0.csv`.
Loading predictions from `/output/mljarsupervised_compete.openml_s_271.test.docker.20201203T093820/predictions/mljarsupervised_compete.wine-quality-white.0.csv`.
Job `local.wine-quality-white.0.mljarsupervised_compete` failed with error: y_true and y_pred contain different number of classes 6, 7. Please provide the true labels explicitly through the labels argument. Classes found in y_true: [0 1 2 3 4 5]
y_true and y_pred contain different number of classes 6, 7. Please provide the true labels explicitly through the labels argument. Classes found in y_true: [0 1 2 3 4 5]
Traceback (most recent call last):
  File "/bench/amlb/job.py", line 62, in start
    result = self._run()
  File "/bench/amlb/benchmark.py", line 383, in _run
    return self.run(framework, framework_name)
  File "/bench/amlb/utils/process.py", line 520, in profiler
    return fn(*args, **kwargs)
  File "/bench/amlb/benchmark.py", line 431, in run
    return results.compute_scores(framework_name, task_config.metrics, result=result, meta_result=meta_result)
  File "/bench/amlb/utils/process.py", line 520, in profiler
    return fn(*args, **kwargs)
  File "/bench/amlb/results.py", line 362, in compute_scores
    score = result.evaluate(metric)
  File "/bench/amlb/results.py", line 392, in evaluate
    return getattr(self, metric)()
  File "/bench/amlb/results.py", line 460, in logloss
    return float(log_loss(self.truth, self.probabilities))
  File "/bench/venv/lib/python3.6/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/bench/venv/lib/python3.6/site-packages/sklearn/metrics/_classification.py", line 2232, in log_loss
    lb.classes_))
ValueError: y_true and y_pred contain different number of classes 6, 7. Please provide the true labels explicitly through the labels argument. Classes found in y_true: [0 1 2 3 4 5]
```

The reason might be missing class label in the `y_true` vector while having all classes in predicted probabilities.

**Comment by sebhrusen** [comment]
@pplonski do you mind trying the following change locally and retry withthat dataset?
If it works I'll apply the fix to all metrics:

in `results.py`
```
class ClassificationResult(Result):
    ...

    def logloss(self):
        return float(log_loss(self.truth, self.probabilities, labels=self.classes))
```
thank you

**Comment by sebhrusen** [comment]
Nevermind, I can reproduce it with constantpredictor...
Well, I don't know how it was not detected before. Fixing this
