### ISSUE TITLE
Removing ignored columns None. argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Innixma** [openml/automlbenchmark#226]
When running the test datasets on master, I ran into the following error:

```
[  237.037763] cloud-init[1419]: Running task iris on framework AutoGluon with config:
[  237.038794] cloud-init[1419]: TaskConfig(framework='AutoGluon', framework_params={}, framework_version='stable', type='classification', name='iris', fold=0, metrics=['logloss', 'acc', 'balacc'], metric='logloss', seed=1560369848, max_runtime_seconds=60, cores=2, max_mem_size_mb=5186, min_vol_size_mb=1000000, input_dir='/s3bucket/input', output_dir='/s3bucket/output/', output_predictions_file='/s3bucket/output/predictions/iris/0/predictions.csv', ext={}, output_metadata_file='/s3bucket/output/predictions/iris/0/metadata.json')
[  237.046569] cloud-init[1419]: Removing ignored columns None.
[  237.047826] cloud-init[1419]: argument of type 'NoneType' is not iterable
[  237.048771] cloud-init[1419]: Traceback (most recent call last):
[  237.049623] cloud-init[1419]:   File "/repo/amlb/benchmark.py", line 444, in run
[  237.050610] cloud-init[1419]:     meta_result = self.benchmark.framework_module.run(self._dataset, task_config)
[  237.051922] cloud-init[1419]:   File "/repo/frameworks/AutoGluon/__init__.py", line 15, in run
[  237.053069] cloud-init[1419]:     train=dict(data=dataset.train.data),
[  237.053952] cloud-init[1419]:   File "/repo/amlb/utils/process.py", line 521, in profiler
[  237.055003] cloud-init[1419]:     return fn(*args, **kwargs)
[  237.055851] cloud-init[1419]:   File "/repo/amlb/datasets/openml.py", line 100, in train
[  237.055947] cloud-init[1419]:     self._ensure_loaded()
[  237.056063] cloud-init[1419]:   File "/repo/amlb/utils/process.py", line 521, in profiler
[  237.056146] cloud-init[1419]:     return fn(*args, **kwargs)
[  237.056221] cloud-init[1419]:   File "/repo/amlb/datasets/openml.py", line 155, in _ensure_loaded
[  237.056298] cloud-init[1419]:     self._load_split()
[  237.056367] cloud-init[1419]:   File "/repo/amlb/datasets/openml.py", line 163, in _load_split
[  237.056451] cloud-init[1419]:     self._prepare_split_data(train_path, test_path)
[  237.056539] cloud-init[1419]:   File "/repo/amlb/datasets/openml.py", line 182, in _prepare_split_data
[  237.056615] cloud-init[1419]:     col_selector, attributes = zip(*[(i, a) for i, a in enumerate(ds['attributes'])
[  237.056689] cloud-init[1419]:   File "/repo/amlb/datasets/openml.py", line 183, in <listcomp>
[  237.056765] cloud-init[1419]:     if a[0] not in self._oml_dataset.ignore_attribute])
[  237.056842] cloud-init[1419]: TypeError: argument of type 'NoneType' is not iterable
[  237.056931] cloud-init[1419]: Removing ignored columns None.
[  237.057001] cloud-init[1419]: Job `local.test.test.iris.0.AutoGluon` failed with error: argument of type 'NoneType' is not iterable
```

@sebhrusen I'm guessing this issue is from the recent `ignored_columns` commit (#224) and could be fixed by checking for `None` and setting to `[]` if `None`.

The command I used to run:
```
runbenchmark.py AutoGluon test -m aws -f 0
```

As a question, do you have unit tests that check for these things? It might be helpful to have a unit test run the test datasets on a generic framework (such as random forest) to identify these issues before they are merged.

**Comment by PGijsbers** [comment]
Related #223.

It's an oversight, we caught it for one instance but failed to catch this one, sorry about that. I'm pushing a fix to master soon.

**Comment by PGijsbers** [comment]
> As a question, do you have unit tests that check for these things? It might be helpful to have a unit test run the test datasets on a generic framework (such as random forest) to identify these issues before they are merged.

Our current test coverage is practically non-existent. It's high on our list of priorities, but didn't have the time to do both that and the new features for the next release :( Alongside unit tests we also test with a set of validation datasets, but that set did not have a dataset with `ignore_attributes`.

**Comment by Innixma** [comment]
Thanks! That fixed the issue, however I've found a separate issue that I've noted in #229.
