### ISSUE TITLE
Refactor OpenML integration to leverage OpenML client also to load data.

### ISSUE THREAD

**Issue by sebhrusen** [openml/automlbenchmark#282]
OpenML client is currently used to extract metadata and download data, but for some legacy reason (issues with an older version probably), data are loaded using the `arff` library.
If the OpenML client now provides everything needed, the `amlb` module should also use it to load the data correctly.

**Comment by PGijsbers** [comment]
The latest version (`0.12`) is much more mature than the one we started out with (I believe `0.7`). It includes e.g. pandas support with correct dtypes. OpenML will soon switch over from `arff` to `parquet` by default, which should make data loading quicker/less memory intensive. However we'll still allow `arff` downloads - but perhaps we should see if other frameworks that currently rely on the data file can work with parquet as well (this is a separate issue).

**Comment by Innixma** [comment]
Is there a path forward to attempt an S3-only usage of data loading, to avoid interacting with openml server? I've noticed that running parallel benchmarks or starting trials too quickly will get OpenML errors that wouldn't occur if we were accessing the S3 files directly. This makes using AutoMLBenchmark fairly difficult as about ~1/4th of the benchmark runs I've done have many failures due to the server errors, and if someone else is using AutoMLBenchmark at the same time, we may cause errors in each-other's runs due to overloaded servers.

**Comment by Innixma** [comment]
Example of the exception:

```
[INFO] [amlb:04:52:12.383] Running `AutoGluon_bestquality:latest` on `ag` benchmarks in `local` mode.
[INFO] [amlb.frameworks.definitions:04:52:12.418] Loading frameworks definitions from /repo/resources/frameworks.yaml.
[INFO] [amlb.resources:04:52:12.493] Loading benchmark constraint definitions from /repo/resources/constraints.yaml.
[INFO] [amlb.benchmarks.file:04:52:12.499] Loading benchmark definitions from /repo/resources/benchmarks/ag.yaml.
[INFO] [amlb.job:04:52:12.550] 
-----------------------------------------------------------
Starting job local.ag.4h8c.abalone.0.AutoGluon_bestquality.
[INFO] [amlb.utils.process:04:52:12.550] [local.ag.4h8c.abalone.0.AutoGluon_bestquality] CPU Utilization: 30.7%
[INFO] [amlb.utils.process:04:52:12.552] [local.ag.4h8c.abalone.0.AutoGluon_bestquality] Memory Usage: 2.5%
[INFO] [amlb.utils.process:04:52:12.552] [local.ag.4h8c.abalone.0.AutoGluon_bestquality] Disk Usage: 4.4%
[INFO] [root:04:52:12.553] Starting [get] request for the URL https://www.openml.org/api/v1/xml/task/359944
[ERROR] [amlb.job:04:52:12.978] Job `local.ag.4h8c.abalone.0.AutoGluon_bestquality` failed with error: https://www.openml.org/api/v1/xml/task/359944 returned code 107: Database connection error. Usually due to high server load. Please wait for N seconds and try again. - None
[ERROR] [amlb.job:04:52:12.978] https://www.openml.org/api/v1/xml/task/359944 returned code 107: Database connection error. Usually due to high server load. Please wait for N seconds and try again. - None
Traceback (most recent call last):
  File "/repo/venv/lib/python3.7/site-packages/openml/tasks/functions.py", line 71, in _get_cached_task
    with io.open(os.path.join(tid_cache_dir, "task.xml"), encoding="utf8") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/s3bucket/input/org/openml/www/tasks/359944/task.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/repo/venv/lib/python3.7/site-packages/openml/tasks/functions.py", line 373, in _get_task_description
    return _get_cached_task(task_id)
  File "/repo/venv/lib/python3.7/site-packages/openml/tasks/functions.py", line 75, in _get_cached_task
    raise OpenMLCacheException("Task file for tid %d not " "cached" % tid)
openml.exceptions.OpenMLCacheException: Task file for tid 359944 not cached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/repo/amlb/job.py", line 69, in start
    result = self._run()
  File "/repo/amlb/benchmark.py", line 396, in _run
    self.load_data()
  File "/repo/amlb/utils/process.py", line 521, in profiler
    return fn(*args, **kwargs)
  File "/repo/amlb/benchmark.py", line 384, in load_data
    self._dataset = Benchmark.data_loader.load(DataSourceType.openml_task, task_id=self._task_def.openml_task_id, fold=self.fold)
  File "/repo/amlb/datasets/__init__.py", line 21, in load
    return self.openml_loader.load(*args, **kwargs)
  File "/repo/amlb/utils/process.py", line 521, in profiler
    return fn(*args, **kwargs)
  File "/repo/amlb/datasets/openml.py", line 37, in load
    task = oml.tasks.get_task(task_id)
  File "/repo/venv/lib/python3.7/site-packages/openml/tasks/functions.py", line 365, in get_task
    raise e
  File "/repo/venv/lib/python3.7/site-packages/openml/tasks/functions.py", line 349, in get_task
    task = _get_task_description(task_id)
  File "/repo/venv/lib/python3.7/site-packages/openml/tasks/functions.py", line 378, in _get_task_description
    task_xml = openml._api_calls._perform_api_call("task/%d" % task_id, "get")
  File "/repo/venv/lib/python3.7/site-packages/openml/_api_calls.py", line 62, in _perform_api_call
    __check_response(response, url, file_elements)
  File "/repo/venv/lib/python3.7/site-packages/openml/_api_calls.py", line 143, in __check_response
    raise __parse_server_exception(response, url, file_elements=file_elements)
openml.exceptions.OpenMLServerException: https://www.openml.org/api/v1/xml/task/359944 returned code 107: Database connection error. Usually due to high server load. Please wait for N seconds and try again. - None
```

**Comment by sebhrusen** [comment]
@Innixma yes, we're perfectly aware of this issue.
I'll implement a workaround right after this PR, but our future plan is definitely to use s3 as the openml cache.
