### ISSUE TITLE
AWS parallel option bug

### ISSUE THREAD

**Issue by Innixma** [openml/automlbenchmark#316]
I just updated to latest mainline (was previously using an older branch that was 70 commits behind).

When I try to run in AWS mode and specifying `-p X`, I get an error:

```
python3 runbenchmark.py AutoGluon test -m aws -p 2
```

Error:
```
Running benchmark `AutoGluon` on `test` framework in `aws` mode.
Loading frameworks definitions from ['/home/ubuntu/benchmark/ag-2021_05_31_infopt/automlbenchmark/resources/frameworks.yaml'].
Loading benchmark constraint definitions from ['/home/ubuntu/benchmark/ag-2021_05_31_infopt/automlbenchmark/resources/constraints.yaml'].
Loading benchmark definitions from /home/ubuntu/benchmark/ag-2021_05_31_infopt/automlbenchmark/resources/benchmarks/test.yaml.
Framework AutoGluon [stable] is not installed.
Traceback (most recent call last):
  File "../automlbenchmark/runbenchmark.py", line 178, in <module>
    res = bench.run(args.task, args.fold)
  File "/home/ubuntu/benchmark/ag-2021_05_31_infopt/automlbenchmark/amlb/runners/aws.py", line 201, in run
    return super().run(task_name, fold)
  File "/home/ubuntu/benchmark/ag-2021_05_31_infopt/automlbenchmark/amlb/benchmark.py", line 196, in run
    assert self._is_setup_done(), f"Framework {self.framework_name} [{self.framework_def.version}] is not installed."
AssertionError: Framework AutoGluon [stable] is not installed.
```

This also happens with other frameworks (using same code as in README):

```
python3 runbenchmark.py AUTOWEKA test -m aws -p 4
```

```
Running benchmark `AUTOWEKA` on `test` framework in `aws` mode.
Loading frameworks definitions from ['/home/ubuntu/benchmark/ag-2021_05_31_infopt/automlbenchmark/resources/frameworks.yaml'].
Loading benchmark constraint definitions from ['/home/ubuntu/benchmark/ag-2021_05_31_infopt/automlbenchmark/resources/constraints.yaml'].
Loading benchmark definitions from /home/ubuntu/benchmark/ag-2021_05_31_infopt/automlbenchmark/resources/benchmarks/test.yaml.
Framework AutoWEKA [stable] is not installed.
Traceback (most recent call last):
  File "../automlbenchmark/runbenchmark.py", line 178, in <module>
    res = bench.run(args.task, args.fold)
  File "/home/ubuntu/benchmark/ag-2021_05_31_infopt/automlbenchmark/amlb/runners/aws.py", line 201, in run
    return super().run(task_name, fold)
  File "/home/ubuntu/benchmark/ag-2021_05_31_infopt/automlbenchmark/amlb/benchmark.py", line 196, in run
    assert self._is_setup_done(), f"Framework {self.framework_name} [{self.framework_def.version}] is not installed."
AssertionError: Framework AutoWEKA [stable] is not installed.
```

It does not error if I don't specify `-p` at all (it will create a single EC2 instance that runs everything sequentially).

Additionally, if I run a benchmark that installs the framework, I can then run the commands that previously errored for that framework and it works. It seems AutoML Benchmark expects the framework is already installed / setup when called with `-p` specified. This was not previously the case, and ideally it should just setup the framework if necessary instead of raising an exception.

For example, this code works on a fresh install of AutoMLBenchmark:

```
# First install, then run on aws, works without issue
python3 runbenchmark.py AutoGluon -s only
python3 runbenchmark.py AutoGluon test -m aws -p 10
```

**Comment by sebhrusen** [comment]
@Innixma 
The assertion is perfectly legit, it just fails early before trying to run the framework if there was an issue with the framework setup.

> and ideally it should just setup the framework if necessary instead of raising an exception.

this is exactly what it is doing, but if the setup failed, as it is a bash script, the error is swallowed somehow.

Here is actually the real issue:
```
[  163.681770] cloud-init[1479]: Running cmd `/repo/frameworks/AutoGluon/setup.sh /repo 0.0.12`
[  163.752282] cloud-init[1479]: The virtual environment was not created successfully because ensurepip is not
[  163.777879] cloud-init[1479]: /repo/frameworks/AutoGluon/venv/bin/python: No module named pip
[  163.782363] cloud-init[1479]: available.  On Debian/Ubuntu systems, you need to install the python3-venv
[  163.784560] cloud-init[1479]: package using the following command.
[  163.786275] cloud-init[1479]: /repo/frameworks/AutoGluon/../shared/setup.sh: line 42: /repo/frameworks/AutoGluon/venv/bin/pip: No such file or directory
[  163.789515] cloud-init[1479]:     apt-get install python3-venv
[  163.790889] cloud-init[1479]: /repo/frameworks/AutoGluon/../shared/setup.sh: line 42: /repo/frameworks/AutoGluon/venv/bin/pip: No such file or directory
[  163.793997] cloud-init[1479]: /repo/frameworks/AutoGluon/../shared/setup.sh: line 42: /repo/frameworks/AutoGluon/venv/bin/pip: No such file or directory
[  163.796815] cloud-init[1479]: You may need to use sudo with that command.  After installing the python3-venv
[  163.799357] cloud-init[1479]: package, recreate your virtual environment.
[  163.801306] cloud-init[1479]: Failing command: ['/repo/frameworks/AutoGluon/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

we haven't changed anything there recently, maybe an issue with latest `python3-venv`, I'll try to figure out.

**Comment by sebhrusen** [comment]
we've been freezing dependencies recently, it may be the cause.

**Comment by sebhrusen** [comment]
With a larger instance, it works fine for me, even with parallelism enabled.
Actually, I don't see how `-p` could have any impact on this: the user script executed on EC2 instance bootstrap and the framework setup are the same regardless of  parallelization.

**Comment by sebhrusen** [comment]
Gotcha, I thought the error was raised in the EC2 instances, but it occurs in the main one when using `aws` mode: actually it should not be necessary to have the framework installed locally in that case, so the assertion should not triggered here.
