### ISSUE TITLE
Missing dataset ARFF files

### ISSUE THREAD

**Issue by Innixma** [openml/automlbenchmark#318]
Recently, 4 datasets from study 269 and 270 appear to no longer have their ARFF files available, causing them to error when benchmarked.

These datasets are:

Airlines_DepDelay_10M
KDDCup99
QSAR-TID-10980
QSAR-TID-11

Is this expected?

Error message:

```
Starting job local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality.
[INFO] [amlb.benchmark:22:42:09.532] Assigning 8 cores (total=8) for new task Airlines_DepDelay_10M.
[INFO] [amlb.utils.process:22:42:09.532] [MONITORING] [local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality] CPU Utilization: 29.1%
[INFO] [amlb.benchmark:22:42:09.533] Assigning 30925 MB (total=31704 MB) for new Airlines_DepDelay_10M task.
[INFO] [amlb.utils.process:22:42:09.533] [MONITORING] [local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality] Memory Usage: 2.5%
[WARNING] [amlb.benchmark:22:42:09.533] WARNING: Available storage (88953.546875 MB / total=99202.91015625 MB) does not meet requirements (102048 MB)!
[INFO] [amlb.utils.process:22:42:09.533] [MONITORING] [local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality] Disk Usage: 10.3%
[INFO] [root:22:42:09.534] Starting [get] request for the URL https://www.openml.org/api/v1/xml/task/359929
[INFO] [root:22:42:09.952] 0.4182761s taken for [get] request for the URL https://www.openml.org/api/v1/xml/task/359929
[INFO] [root:22:42:09.953] Starting [get] request for the URL https://www.openml.org/api/v1/xml/data/42728
[INFO] [root:22:42:10.265] 0.3119171s taken for [get] request for the URL https://www.openml.org/api/v1/xml/data/42728
[INFO] [root:22:42:10.266] Starting [get] request for the URL https://www.openml.org/api/v1/xml/data/features/42728
[INFO] [root:22:42:10.583] 0.3173161s taken for [get] request for the URL https://www.openml.org/api/v1/xml/data/features/42728
[INFO] [root:22:42:10.584] Starting [get] request for the URL https://www.openml.org/data/v1/download/22044760/Airlines_DepDelay_10M.arff
[INFO] [root:22:43:31.854] 81.2698050s taken for [get] request for the URL https://www.openml.org/data/v1/download/22044760/Airlines_DepDelay_10M.arff
[INFO] [root:22:43:32.162] Starting [get] request for the URL https://www.openml.org//api_splits/get/359929/Task_359929_splits.arff
[INFO] [amlb.utils.process:22:44:09.534] [MONITORING] [local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality] CPU Utilization: 0.7%
[INFO] [amlb.utils.process:22:44:09.534] [MONITORING] [local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality] Memory Usage: 3.7%
[INFO] [amlb.utils.process:22:44:09.534] [MONITORING] [local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality] Disk Usage: 10.7%
[INFO] [root:22:45:02.277] 90.1152575s taken for [get] request for the URL https://www.openml.org//api_splits/get/359929/Task_359929_splits.arff
[INFO] [amlb.utils.process:22:46:27.528] [MONITORING] [local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality] CPU Utilization: 8.0%
[INFO] [amlb.utils.process:22:46:41.145] [MONITORING] [local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality] Memory Usage: 6.7%
[INFO] [amlb.utils.process:22:46:45.502] [MONITORING] [local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality] Disk Usage: 11.5%
[ERROR] [amlb.job:22:48:24.147] Job `local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality` failed with error: Bad @DATA instance format in line -1: TRAIN,
Traceback (most recent call last):
  File "/repo/venv/lib/python3.7/site-packages/openml/tasks/task.py", line 151, in download_split
    split = OpenMLSplit._from_arff_file(cached_split_file)
  File "/repo/venv/lib/python3.7/site-packages/openml/tasks/split.py", line 90, in _from_arff_file
    raise FileNotFoundError("Split arff %s does not exist!" % filename)
FileNotFoundError: Split arff /s3bucket/input/org/openml/www/tasks/359929/datasplits.arff does not exist!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/repo/amlb/job.py", line 92, in start
    self._setup()
  File "/repo/amlb/benchmark.py", line 479, in setup
    self.load_data()
  File "/repo/amlb/benchmark.py", line 449, in load_data
    self._dataset = Benchmark.data_loader.load(DataSourceType.openml_task, task_id=self._task_def.openml_task_id, fold=self.fold)
  File "/repo/amlb/datasets/__init__.py", line 21, in load
    return self.openml_loader.load(*args, **kwargs)
  File "/repo/amlb/utils/process.py", line 702, in profiler
    return fn(*args, **kwargs)
  File "/repo/amlb/datasets/openml.py", line 46, in load
    task = oml.tasks.get_task(task_id, download_qualities=False)
  File "/repo/venv/lib/python3.7/site-packages/openml/tasks/functions.py", line 376, in get_task
    raise e
  File "/repo/venv/lib/python3.7/site-packages/openml/tasks/functions.py", line 371, in get_task
    task.download_split()
  File "/repo/venv/lib/python3.7/site-packages/openml/tasks/task.py", line 155, in download_split
    split = OpenMLSplit._from_arff_file(cached_split_file)
  File "/repo/venv/lib/python3.7/site-packages/openml/tasks/split.py", line 104, in _from_arff_file
    for line in splits:
  File "/repo/venv/lib/python3.7/site-packages/arff.py", line 470, in decode_rows
    raise BadDataFormat(row)
arff.BadDataFormat: Bad @DATA instance format in line -1: TRAIN,
[ERROR] [amlb.job:22:48:24.689] Job `local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality` did not stop gracefully: Job `local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality` was interrupted.
Traceback (most recent call last):
  File "/repo/amlb/job.py", line 142, in stop
    self._cancel()
  File "/repo/amlb/job.py", line 179, in _cancel
    raise_in_thread(self.thread_id, CancelledError(f"Job `{self.name}` was interrupted."))
  File "/repo/amlb/utils/process.py", line 395, in raise_in_thread
    ret = ctypes.pythonapi.PyThreadState_SetAsyncExc(tid, exc_class)
amlb.utils.process.CancelledError: Job `local.ag.1h8c.Airlines_DepDelay_10M.0.AutoGluon_bestquality` was interrupted.

```

**Comment by Innixma** [comment]
I also noticed this same error occurred in 3 folds (fold 1, 2, and 6) of `riccardo` in one of my benchmarks, but not in other benchmarks before or after, which seems quite odd.

**Comment by sebhrusen** [comment]
@PGijsbers can it be related to changes in latest OpenML client?
It looks like we may have the data but only the splits are missing…

```FileNotFoundError: Split arff /s3bucket/input/org/openml/www/tasks/359929/datasplits.arff does not exist!```

**Comment by PGijsbers** [comment]
Since the split information is stored all together in one file, it seems odd that some folds would have it and others don't. It makes me think that in least in that case the issues might be related to the server, but I'm looking into it.

**Comment by PGijsbers** [comment]
The QSAR tasks have been replaced with new ones (on the same dataset):
 - QSAR-TID-11   `13854` -> `360932`
 - QSAR-TID-10980  `14097` -> `360933`

The old tasks are no longer supported ([OpenML#1108](https://github.com/openml/OpenML/issues/1108)).
The other two tasks failed due some internal server state. The split files should be downloadable again ([OpenML#1109](https://github.com/openml/OpenML/issues/1109)).

Study 269 has been updated to use the new QSAR tasks instead. If you still experience issues, please first empty your cache (`~/.openml/cache` by default). If this resolved your issue, feel free to close it. In case you still experience difficulties with these datasets, just let us know.

**Comment by PGijsbers** [comment]
Considering the reaction I assume this issue has been resolved.
