### ISSUE TITLE
NoResultError: parquet must have string column names

### ISSUE THREAD

**Issue by Innixma** [openml/automlbenchmark#357]
Running AutoGluon on latest AutoMLBenchmark mainline, I'm seeing the following error for `kc1`, `MiniBooNE` and `pc4` datasets:

```
NoResultError: parquet must have string column names
```

Looking deeper, it appears that AutoGluon successfully trained on all of the datasets, but at the very end this error occurred.

An example log output of `kc1`:

```
[INFO] [amlb.print:20:51:29.770]                       model  score_test  score_val  pred_time_test  pred_time_val     fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
[INFO] [amlb.print:20:51:30.091] 0   RandomForestGini_BAG_L2    0.866271   0.876279       30.125159      27.074952  1748.063022                 0.112795                0.125331           0.604155            2       True         19
[INFO] [amlb.print:20:51:30.091] 1           CatBoost_BAG_L2    0.865136   0.869832       30.318362      27.270582  1932.345979                 0.305997                0.320961         184.887112            2       True         21
[INFO] [amlb.print:20:51:30.091] 2    NeuralNetFastAI_BAG_L2    0.864438   0.855177       36.343328      32.203115  2255.920542                 6.330963                5.253495         508.461675            2       True         24
[INFO] [amlb.print:20:51:30.091] 3     ExtraTreesGini_BAG_L2    0.861819   0.883482       30.128556      27.078614  1748.063162                 0.116192                0.128994           0.604295            2       True         22
[INFO] [amlb.print:20:51:30.091] 4   RandomForestEntr_BAG_L2    0.860335   0.872031       30.126674      27.074091  1748.162348                 0.114310                0.124470           0.703481            2       True         20
[INFO] [amlb.print:20:51:30.091] 5   RandomForestEntr_BAG_L1    0.860161   0.823200        0.114205       0.122945     0.703191                 0.114205                0.122945           0.703191            1       True          6
[INFO] [amlb.print:20:51:30.091] 6       WeightedEnsemble_L3    0.858153   0.885198       48.502545      46.556897  2479.222977                 0.002307                0.001428           1.611111            3       True         28
[INFO] [amlb.print:20:51:30.092] 7     ExtraTreesEntr_BAG_L1    0.856931   0.830755        0.116041       0.126892     0.606815                 0.116041                0.126892           0.606815            1       True          9
[INFO] [amlb.print:20:51:30.092] 8     ExtraTreesEntr_BAG_L2    0.856233   0.880650       30.128896      27.078642  1748.065247                 0.116532                0.129021           0.606380            2       True         23
[INFO] [amlb.print:20:51:30.092] 9           LightGBM_BAG_L2    0.855709   0.867917       30.549330      27.291773  1810.576451                 0.536966                0.342152          63.117584            2       True         18
[INFO] [amlb.print:20:51:30.092] 10    ExtraTreesGini_BAG_L1    0.852654   0.829666        0.115967       0.127167     0.604753                 0.115967                0.127167           0.604753            1       True          8
[INFO] [amlb.print:20:51:30.092] 11        LightGBMXT_BAG_L2    0.852217   0.868019       30.908712      27.363212  1812.808187                 0.896347                0.413591          65.349320            2       True         17
[INFO] [amlb.print:20:51:30.092] 12  RandomForestGini_BAG_L1    0.847242   0.825959        0.113283       0.123582     0.606750                 0.113283                0.123582           0.606750            1       True          5
[INFO] [amlb.print:20:51:30.092] 13    NeuralNetMXNet_BAG_L2    0.845932   0.859704       47.466799      45.905474  2328.764401                17.454434               18.955853         581.305534            2       True         26
[INFO] [amlb.print:20:51:30.092] 14           XGBoost_BAG_L2    0.841917   0.867360       34.282404      27.656868  1886.498172                 4.270040                0.707247         139.039305            2       True         25
[INFO] [amlb.print:20:51:30.092] 15      WeightedEnsemble_L2    0.841219   0.846631       28.617513      26.020197  1643.165488                 0.004076                0.001404           1.602185            2       True         14
[INFO] [amlb.print:20:51:30.092] 16          CatBoost_BAG_L1    0.840171   0.836735        0.280970       0.423105   142.288422                 0.280970                0.423105         142.288422            1       True          7
[INFO] [amlb.print:20:51:30.092] 17     LightGBMLarge_BAG_L2    0.839298   0.866106       30.813079      27.341600  1895.095656                 0.800715                0.391979         147.636790            2       True         27
[INFO] [amlb.print:20:51:30.092] 18     LightGBMLarge_BAG_L1    0.837902   0.821019        0.748237       0.412104   129.199071                 0.748237                0.412104         129.199071            1       True         13
[INFO] [amlb.print:20:51:30.092] 19   NeuralNetFastAI_BAG_L1    0.832490   0.827754        5.261857       4.340533   533.250644                 5.261857                4.340533         533.250644            1       True         10
[INFO] [amlb.print:20:51:30.092] 20    NeuralNetMXNet_BAG_L1    0.828998   0.832354       17.388370      19.792927   724.453914                17.388370               19.792927         724.453914            1       True         12
[INFO] [amlb.print:20:51:30.092] 21          LightGBM_BAG_L1    0.827776   0.822883        0.501951       0.368770    55.448913                 0.501951                0.368770          55.448913            1       True          4
[INFO] [amlb.print:20:51:30.092] 22        LightGBMXT_BAG_L1    0.824284   0.826437        0.775536       0.420644    49.571754                 0.775536                0.420644          49.571754            1       True          3
[INFO] [amlb.print:20:51:30.093] 23           XGBoost_BAG_L1    0.821142   0.833066        4.588712       0.672483   110.552933                 4.588712                0.672483         110.552933            1       True         11
[INFO] [amlb.print:20:51:30.093] 24    KNeighborsDist_BAG_L2    0.764490   0.759153       30.017735      26.957803  1747.460258                 0.005370                0.008182           0.001391            2       True         16
[INFO] [amlb.print:20:51:30.093] 25    KNeighborsUnif_BAG_L2    0.752270   0.736920       30.017572      26.958381  1747.460871                 0.005208                0.008760           0.002004            2       True         15
[INFO] [amlb.print:20:51:30.093] 26    KNeighborsDist_BAG_L1    0.749825   0.740764        0.003700       0.007258     0.001921                 0.003700                0.007258           0.001921            1       True          2
[INFO] [amlb.print:20:51:30.093] 27    KNeighborsUnif_BAG_L1    0.749302   0.730699        0.003535       0.011210     0.169784                 0.003535                0.011210           0.169784            1       True          1
[INFO] [amlb.print:20:51:30.093] parquet must have string column names
[INFO] [amlb.print:20:51:30.477] 
[INFO] [amlb.print:20:51:30.477] Traceback (most recent call last):
[INFO] [amlb.print:20:51:30.477] 
[INFO] [amlb.print:20:51:30.477]   File "/repo/frameworks/shared/callee.py", line 90, in call_run
[INFO] [amlb.print:20:51:30.477] 
[INFO] [amlb.print:20:51:30.477]     res[name] = serialize_data(arr, path)
[INFO] [amlb.print:20:51:30.477] 
[INFO] [amlb.print:20:51:30.477]   File "/repo/amlb/utils/process.py", line 702, in profiler
[INFO] [amlb.print:20:51:30.477] 
[INFO] [amlb.print:20:51:30.478]     return fn(*args, **kwargs)
[INFO] [amlb.print:20:51:30.478] 
[INFO] [amlb.print:20:51:30.478]   File "/repo/frameworks/shared/serialization.py", line 47, in serialize_data
[INFO] [amlb.print:20:51:30.478] 
[INFO] [amlb.print:20:51:30.478]     data.to_parquet(path, compression=ser_config.pandas_parquet_compression)
[INFO] [amlb.print:20:51:30.478] 
[INFO] [amlb.print:20:51:30.478]   File "/repo/frameworks/AutoGluon/venv/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
[INFO] [amlb.print:20:51:30.478] 
[INFO] [amlb.print:20:51:30.478]     return func(*args, **kwargs)
[INFO] [amlb.print:20:51:30.478] 
[INFO] [amlb.print:20:51:30.478]   File "/repo/frameworks/AutoGluon/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 2685, in to_parquet
[INFO] [amlb.print:20:51:30.478] 
[INFO] [amlb.print:20:51:30.478]     **kwargs,
[INFO] [amlb.print:20:51:30.478] 
[INFO] [amlb.print:20:51:30.478]   File "/repo/frameworks/AutoGluon/venv/lib/python3.7/site-packages/pandas/io/parquet.py", line 419, in to_parquet
[INFO] [amlb.print:20:51:30.478] 
[INFO] [amlb.print:20:51:30.478]     **kwargs,
[INFO] [amlb.print:20:51:30.479] 
[INFO] [amlb.print:20:51:30.479]   File "/repo/frameworks/AutoGluon/venv/lib/python3.7/site-packages/pandas/io/parquet.py", line 167, in write
[INFO] [amlb.print:20:51:30.479] 
[INFO] [amlb.print:20:51:30.479]     self.validate_dataframe(df)
[INFO] [amlb.print:20:51:30.479] 
[INFO] [amlb.print:20:51:30.479]   File "/repo/frameworks/AutoGluon/venv/lib/python3.7/site-packages/pandas/io/parquet.py", line 129, in validate_dataframe
[INFO] [amlb.print:20:51:30.479] 
[INFO] [amlb.print:20:51:30.479]     raise ValueError("parquet must have string column names")
[INFO] [amlb.print:20:51:30.479] 
[INFO] [amlb.print:20:51:30.479] ValueError: parquet must have string column names
[INFO] [amlb.print:20:51:30.479] 
[INFO] [amlb.print:20:51:30.479] 
[INFO] [amlb.print:20:51:30.480] 
[ERROR] [amlb.benchmark:20:51:30.481] parquet must have string column names
Traceback (most recent call last):
  File "/repo/amlb/benchmark.py", line 511, in run
    meta_result = self.benchmark.framework_module.run(self._dataset, task_config)
  File "/repo/frameworks/AutoGluon/__init__.py", line 24, in run
    input_data=data, dataset=dataset, config=config)
  File "/repo/frameworks/shared/caller.py", line 140, in run_in_venv
    raise NoResultError(res.error_message)
amlb.results.NoResultError: parquet must have string column names

```

The error seems to be coming from AutoMLBenchmark and not AutoGluon, at least from my initial guess.

**Comment by PGijsbers** [comment]
As the error implies, pandas can not serialize datasets to parquet format if they don't have string columns. The serialization happens [here](https://github.com/openml/automlbenchmark/blob/8f3a83c252d84a1310b168dad34cd263524a6c3c/frameworks/shared/serialization.py#L44-L47). I consider it a bug in the benchmark framework as I don't think we specify any column names need to be supplied.

@sebhrusen Because column names are not enforced here, I assume that similar to numpy arrays the content of the dataframes is interpreted based on order? Do we want then fix this with e.g. `df.columns = [str(c) for c in df.columns]` if columns are non-string? We could also assign more meaningful names at [callee](https://github.com/openml/automlbenchmark/blob/8f3a83c252d84a1310b168dad34cd263524a6c3c/frameworks/shared/callee.py#L86-L90) level (of course under the assumption the framework passes the dataframe with correct column order).

**Comment by sebhrusen** [comment]
@PGijsbers looking into it: it looks like for parquet serialization, we're missing autoconversion of lists into pd.Series.
It doesn't occur on all datasets though, investigating.

**Comment by sebhrusen** [comment]
with kc1:
```
('#####', Index([False, True], dtype='object'))
('*****', 'probabilities', <class 'pandas.core.frame.DataFrame'>,          False     True
481   0.983783  0.016217
1669  0.982909  0.017091
```
^^ I guess this fails because the column names are interpreted as boolean values (a problem we've been having with pandas for a while)

with kc2:
```
('#####', Index(['no', 'yes'], dtype='object'))
('*****', 'probabilities', <class 'pandas.core.frame.DataFrame'>,            no       yes
293  0.822302  0.177698
102  0.822302  0.177698
```
