### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hengzhe-zhang** [openml/automlbenchmark#365]
I have successfully completed small scale experiments. However, when I am trying to apply my AutoML algorithm on medium scale experiments, the experimental script will raise the following error:
```python
Traceback (most recent call last):
  File "/home/zhanghz/miniforge3/lib/python3.8/site-packages/openml/tasks/task.py", line 135, in _download_split
    with io.open(cache_file, encoding="utf8"):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhanghz/.openml/cache/org/openml/www/tasks/7592/datasplits.arff'
```
As a result, how can I solve this problem?

**Comment by PGijsbers** [comment]
Can you provide us with the command used to run the benchmark, as well as the full stack trace? That would help us identify the issue.

**Comment by zhenlingcn** [comment]
Of course!
This is my command:
```python
python3.8 -u runbenchmark.py EvolutionaryForest medium 1h4c --parallel 96
```
And this is the full stack trace:
```python
Traceback (most recent call last):
  File "/home/zhanghz/miniforge3/lib/python3.8/site-packages/openml/tasks/task.py", line 151, in download_split
    split = OpenMLSplit._from_arff_file(cached_split_file)
  File "/home/zhanghz/miniforge3/lib/python3.8/site-packages/openml/tasks/split.py", line 90, in _from_arff_file
    raise FileNotFoundError("Split arff %s does not exist!" % filename)
FileNotFoundError: Split arff /home/zhanghz/.openml/cache/org/openml/www/tasks/7592/datasplits.arff does not exist!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/adaptive-GP/automlbenchmark/amlb/job.py", line 94, in start
    self._setup()
  File "/tmp/adaptive-GP/automlbenchmark/amlb/benchmark.py", line 482, in setup
    self.load_data()
  File "/tmp/adaptive-GP/automlbenchmark/amlb/benchmark.py", line 452, in load_data
    self._dataset = Benchmark.data_loader.load(DataSourceType.openml_task, task_id=self._task_def.openml_task_id, fold=self.fold)
  File "/tmp/adaptive-GP/automlbenchmark/amlb/datasets/__init__.py", line 21, in load
    return self.openml_loader.load(*args, **kwargs)
  File "/tmp/adaptive-GP/automlbenchmark/amlb/utils/process.py", line 702, in profiler
    return fn(*args, **kwargs)
  File "/tmp/adaptive-GP/automlbenchmark/amlb/datasets/openml.py", line 46, in load
    task = oml.tasks.get_task(task_id, download_qualities=False)
  File "/home/zhanghz/miniforge3/lib/python3.8/site-packages/openml/tasks/functions.py", line 376, in get_task
    raise e
  File "/home/zhanghz/miniforge3/lib/python3.8/site-packages/openml/tasks/functions.py", line 371, in get_task
    task.download_split()
  File "/home/zhanghz/miniforge3/lib/python3.8/site-packages/openml/tasks/task.py", line 155, in download_split
    split = OpenMLSplit._from_arff_file(cached_split_file)
  File "/home/zhanghz/miniforge3/lib/python3.8/site-packages/openml/tasks/split.py", line 91, in _from_arff_file
    file_data = arff.load(open(filename), return_type=arff.DENSE_GEN)
  File "/home/zhanghz/miniforge3/lib/python3.8/site-packages/arff.py", line 1059, in load
    return decoder.decode(fp, encode_nominal=encode_nominal,
  File "/home/zhanghz/miniforge3/lib/python3.8/site-packages/arff.py", line 896, in decode
    raise e
  File "/home/zhanghz/miniforge3/lib/python3.8/site-packages/arff.py", line 892, in decode
    return self._decode(s, encode_nominal=encode_nominal,
  File "/home/zhanghz/miniforge3/lib/python3.8/site-packages/arff.py", line 859, in _decode
    raise BadLayout()
arff.BadLayout: Invalid layout of the ARFF file, at line 0.
```

**Comment by PGijsbers** [comment]
Sorry for never following up on this. I ran `python runbenchmark.py constantpredictor medium test -f 0 -t adult` locally now (adult is task 7592 which gave the error), after clearing my OpenML cache, and that worked fine. I have to assume that either at the time OpenML had an incorrect file (possibly corrupted during download) or there was some other incompatibility, which by now is resolved. Given the time the issue has been open, I assume it's fine to close it with this confirmation.

Should you still experience this issue, then feel free to re-open and I'll promise to be more helpful this time ^^"
