### ISSUE TITLE
Upgrade sklearn to be >=0.21

### ISSUE THREAD

**Issue by Innixma** [openml/automlbenchmark#74]
I am currently attempting to integrate AutoGluon into automlbenchmark, however I am facing some issues regarding sklearn version requirements.

If I try to run with sklearn >= 0.21, I get this exception:

```
Traceback (most recent call last):
  File "../automlbenchmark/runbenchmark.py", line 7, in <module>
    import amlb.logger
  File "/home/ubuntu/workspace/automlbenchmark/amlb/__init__.py", line 8, in <module>
    from .benchmark import Benchmark
  File "/home/ubuntu/workspace/automlbenchmark/amlb/benchmark.py", line 19, in <module>
    from .openml import Openml
  File "/home/ubuntu/workspace/automlbenchmark/amlb/openml.py", line 9, in <module>
    import openml as oml
  File "/home/ubuntu/workspace/autogluon/venv/lib/python3.6/site-packages/openml/__init__.py", line 22, in <module>
    from . import runs
  File "/home/ubuntu/workspace/autogluon/venv/lib/python3.6/site-packages/openml/runs/__init__.py", line 3, in <module>
    from .functions import (run_model_on_task, run_flow_on_task, get_run, list_runs,
  File "/home/ubuntu/workspace/autogluon/venv/lib/python3.6/site-packages/openml/runs/functions.py", line 21, in <module>
    from ..flows import sklearn_to_flow, get_flow, flow_exists, _check_n_jobs, \
  File "/home/ubuntu/workspace/autogluon/venv/lib/python3.6/site-packages/openml/flows/__init__.py", line 3, in <module>
    from .sklearn_converter import sklearn_to_flow, flow_to_sklearn, _check_n_jobs
  File "/home/ubuntu/workspace/autogluon/venv/lib/python3.6/site-packages/openml/flows/sklearn_converter.py", line 20, in <module>
    from sklearn.utils.fixes import signature
ImportError: cannot import name 'signature'
```

AutoSklearn 0.6.0 also requires sklearn >= 0.21, and latest TPOT requires sklearn >= 0.22

Would it be possible to make automlbenchmark compatible with newer sklearn versions?

Best,
Nick

**Comment by sebhrusen** [comment]
Hi @Innixma, if you follow <https://github.com/openml/automlbenchmark/tree/master/frameworks/RandomForest> or <https://github.com/openml/automlbenchmark/tree/master/examples/custom/extensions/Stacking> integration examples, you should be able to use any library version for your `AutoGluon` integration.
This has been raised in <https://github.com/openml/automlbenchmark/issues/49> and addressed by <https://github.com/openml/automlbenchmark/pull/60>.
See also <https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#frameworks-with-python-api> for a quick explanation.

**Comment by sebhrusen** [comment]
> AutoSklearn 0.6.0 also requires sklearn >= 0.21, and latest TPOT requires sklearn >= 0.22

I agree that we need to update those integrations and upgrade their version+requirements. Will create separate ticket for those.

**Comment by Innixma** [comment]
Thanks Seb for the detailed instructions! I'll take a look at it and get back to you with a PR in the coming weeks.

**Comment by Innixma** [comment]
I'll mark this issue as closed unless I experience further difficulties.
